//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutJsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Books = new HashSet<Book>();
            this.Locations = new HashSet<Location>();
            this.Prices = new HashSet<Price>();
            this.Suburbs = new HashSet<Suburb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<Suburb> Suburbs { get; set; }
    }
}
