//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutJsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public Nullable<decimal> Adult_Single_Ticket { get; set; }
        public Nullable<decimal> Adult_Return_Ticket { get; set; }
        public Nullable<decimal> Child_Single_Ticket { get; set; }
        public Nullable<decimal> Child_Return_Ticket { get; set; }
        public int City_Id { get; set; }
    
        public virtual City City { get; set; }
    }
}
