//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutJsDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoyaleContext : DbContext
    {
        public RoyaleContext()
            : base("name=RoyaleContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Ref_Generate> Ref_Generate { get; set; }
        public virtual DbSet<ShuttleTimeTable> ShuttleTimeTables { get; set; }
        public virtual DbSet<Suburb> Suburbs { get; set; }
        public virtual DbSet<TimeType> TimeTypes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
