//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutJsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShuttleTimeTable
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> TimeTypeId { get; set; }
    
        public virtual TimeType TimeType { get; set; }
    }
}
