//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutJsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeType
    {
        public TimeType()
        {
            this.ShuttleTimeTables = new HashSet<ShuttleTimeTable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<ShuttleTimeTable> ShuttleTimeTables { get; set; }
    }
}
